import type { Metadata } from 'next'
import LocalFont from 'next/font/local'
import './globals.css'
import {ProvidersSession} from "@/utilities/ProvidersSession";
import React from "react";
import {StoreProvider} from "@/store/StoreProvider";
require('dotenv').config();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const myFont = LocalFont({src: '../assets/fontFamily/Geologica/Geologica.ttf'})
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={myFont.style}>
        <StoreProvider>
            <ProvidersSession>
                <main>{children}</main>
            </ProvidersSession>
        </StoreProvider>
      </body>
    </html>
  )
}