import type { Metadata } from 'next'
import './globals.css'
import {ProvidersSession} from "@/utilities/ProvidersSession";
import React from "react";
import {StoreProvider} from "@/store/StoreProvider";
import {inter, geologica} from "@/styles/fonts";
import {TheHeader} from "@/modules";
require('dotenv').config();

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${geologica.variable}`}>
        <StoreProvider>
            <ProvidersSession>
                <main> <TheHeader/> {children}</main>
            </ProvidersSession>
        </StoreProvider>
      </body>
    </html>
  )
}